version: "3.0" 
services: 
  express: 
    build: express
    links: 
      - mongodb
    ports: 
      - "8080:8080"
  mongodb: 
    image: mongo
    ports: 
      - "27017:27017"
  vue: 
    build: vue
    links: 
      - express
    ports: 
      - "9090:9090"
